apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-k8s-jenkins
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-23e6328a.efs.us-west-2.amazonaws.com
    path: "/"
